In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.model_selection import train_test_split

In [34]:
set_train = pd.read_csv('data_set.csv')
test_values = pd.read_csv('data_test.csv')
test_values.iloc[:, 1:]

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,...,plan_configuration_a,plan_configuration_c,plan_configuration_d,plan_configuration_f,plan_configuration_m,plan_configuration_n,plan_configuration_o,plan_configuration_q,plan_configuration_s,plan_configuration_u
0,17,596,11307,3,20,7,6,0.830916,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
1,6,141,11987,2,25,13,5,0.830916,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
2,22,19,10044,2,5,4,5,0.830916,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
3,26,39,633,1,0,19,3,0.830916,0.842405,0.062232,...,0,0,0,0,0,0,0,0,0,1
4,17,289,7970,3,15,8,7,0.830916,0.842405,0.234022,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86863,4,605,3623,3,70,20,6,0.830916,0.842405,0.234022,...,0,0,0,0,0,0,0,0,0,1
86864,10,1407,11907,3,25,6,7,0.136817,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
86865,22,1136,7712,1,50,3,3,0.830916,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
86866,6,1041,912,2,5,9,5,0.830916,0.842405,0.703746,...,0,0,0,0,0,0,0,0,0,1
86867,26,36,6436,2,10,11,4,0.830916,0.842405,0.234022,...,0,0,0,0,0,0,0,0,0,1

In [35]:
features = ['age',
            'geo_level_1_id',
            'geo_level_2_id',
            'geo_level_3_id',
            'count_families',
            'base_condition',
            'volume_percentage',
            'area_percentage',
            'height_percentage', 
            'geolevel_grouped_age_mean',
            'geolevel_grouped_height_mean',
            'geolevel_grouped_area_mean',
            'construction_type_grouped_age_mean',
            'construction_type_grouped_height_mean',
            'construction_type_grouped_area_mean',
            'count_floors_pre_eq',
            'has_secondary_use', 'has_secondary_use_agriculture', 'has_secondary_use_hotel',
            'has_secondary_use_rental', 'has_secondary_use_institution', 'has_secondary_use_school',
            'has_secondary_use_industry', 'has_secondary_use_health_post', 'has_secondary_use_gov_office',
            'has_secondary_use_use_police', 'has_secondary_use_other', 
            'has_superstructure_rc_engineered', 'has_superstructure_rc_non_engineered', 'has_superstructure_cement_mortar_brick',
            'has_superstructure_cement_mortar_stone', 'has_superstructure_mud_mortar_brick', 'has_superstructure_mud_mortar_stone',
            'has_superstructure_stone_flag', 'has_superstructure_timber', 'has_superstructure_adobe_mud', 
            'has_superstructure_bamboo', 'has_superstructure_other',
            'land_surface_condition_n', 'land_surface_condition_o', 'land_surface_condition_t',
            'foundation_type_h', 'foundation_type_i', 'foundation_type_r', 'foundation_type_u', 'foundation_type_w',
            'roof_type_n', 'roof_type_q', 'roof_type_x',
            'ground_floor_type_f', 'ground_floor_type_m', 'ground_floor_type_v', 'ground_floor_type_x', 'ground_floor_type_z',
            'other_floor_type_j', 'other_floor_type_q', 'other_floor_type_s', 'other_floor_type_x',
            'position_j', 'position_o', 'position_s', 'position_t',
            'plan_configuration_a', 'plan_configuration_c', 'plan_configuration_d', 'plan_configuration_f', 'plan_configuration_m', 'plan_configuration_n', 'plan_configuration_o', 'plan_configuration_q', 'plan_configuration_s', 'plan_configuration_u',
            'damage_grade']

In [36]:
train, test = train_test_split(set_train, test_size = 0.20, shuffle = False)

train_values_subset = train.iloc[:, 0:-1]
train_labels = train.loc[:, 'damage_grade']

test_values_subset = test.iloc[:, 0:-1]
test_labels = test.loc[:, 'damage_grade']

In [37]:
train_values_subset = pd.get_dummies(train_values_subset)

In [38]:
rf_model = RandomForestClassifier(random_state=1, n_estimators=30, max_depth=300)

In [39]:
rf_model.fit(train_values_subset, train_labels.values.ravel())

RandomForestClassifier(max_depth=300, n_estimators=30, random_state=1)

In [40]:
preds = rf_model.predict(test_values_subset)
f1_score(test_labels, preds, average='micro')

0.7157959363788109

In [41]:
test_values_subset = test_values[features[0:-1]]
test_values_subset = pd.get_dummies(test_values_subset)

In [42]:
predictions = rf_model.predict(test_values_subset)

In [43]:
submission_format = pd.read_csv('submission_format.csv',index_col='building_id')

In [44]:
my_submission = pd.DataFrame(data=predictions, columns=submission_format.columns,
                            index=submission_format.index)

In [45]:
my_submission.head()

             damage_grade
building_id
300051                2.0
99355                 2.0
890251                2.0
745817                1.0
421793                3.0

In [46]:
my_submission.to_csv('submissionRF.csv')